server:
  port: 60083

spring:
  mvc:
   view:
      prefix: /WEB-INF/view/  # JSP 파일 경로
      suffix: .jsp  # JSP 파일 확장자
  devtools:
   livereload:
      enabled: true  # LiveReload 활성화 (자동 새로고침)
   restart:
      enabled: true  # 코드 변경 시 자동 서버 재시작

api:
  base-url: http://58.127.241.84:60085

#  http:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true

# url: jdbc:mysql://192.168.0.10:63306/nomer_hacker_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Seoul
