server:
  port: 60083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.10:63306/nomer_hacker_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: nomer_admin1
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:
    view:
      prefix: /WEB-INF/view/  # JSP 파일 경로
      suffix: .jsp  # JSP 파일 확장자

  devtools:
    livereload:
      enabled: true  # LiveReload 활성화 (자동 새로고침)
    restart:
      enabled: true  # 코드 변경 시 자동 서버 재시작

  # ✅ 파일 업로드 크기 제한 설정 추가
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

api:
  base-url: http://localhost:60085

#  http:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true

# url: jdbc:mysql://192.168.0.10:63306/nomer_hacker_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Seoul
